2026-08-13_14-59-59_conv_8213128f_i_had_some_interesti.md:
	cat 2026-08-13_14-59-59_conv_8213128f_i_had_some_interesti.jsonl | jq .message.content | tail -1 | sed 's/\\n/\n/g' | sed 's/\\"/\"/g' > 2026-08-13_14-59-59_conv_8213128f_i_had_some_interesti.md

