services:
  nixos:
    build: ./nixos
    environment:
      LANG: "C.UTF-8"
  dev:
    build: .
    volumes:
      - ./home:/home
    working_dir: /home
  duck:
    build: ./duck
    environment:
      LANG: "C.UTF-8"
    volumes:
      - ../duck.ai:/home
    working_dir: /home
