build:	code-server
	docker compose build
up:
	docker compose up -d
dev:
	docker compose exec vscode bash
down:
	docker compose down
code-server:
	git clone https://github.com/coder/code-server.git
clean:
	rm -rf code-server

