all:
	echo "# phi-3 " > README.md
	echo "[https://arxiv.org/abs/2404.14219](https://arxiv.org/abs/2404.14219)" >> README.md
	uv run ask_phi-3-mini.py > ask_phi-3-mini.md
	uv run ask_math.py > ask_math.md
