//! Default library crate generated by cargo
//!
//! ```sh
//! % cargo new --lib default
//!    Creating library `default` package
//! note: see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
//! % ls default/**/*
//! default/Cargo.toml	default/src/lib.rs
//!
//! default/src:
//!
//! % cat default/Cargo.toml
//! [package]
//! name = "default"
//! version = "0.1.0"
//! edition = "2024"
//!
//! [dependencies]
//!
//! % cat -n default/src/lib.rs
//!     1	pub fn add(left: u64, right: u64) -> u64 {
//!     2	    left + right
//!     3	}
//!     4
//!     5	#[cfg(test)]
//!     6	mod tests {
//!     7	    use super::*;
//!     8
//!     9	    #[test]
//!    10	    fn it_works() {
//!    11	        let result = add(2, 2);
//!    12	        assert_eq!(result, 4);
//!    13	    }
//!    14	}
//! ```
//!
pub fn add(left: u64, right: u64) -> u64 {
    left + right
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let result = add(2, 2);
        assert_eq!(result, 4);
    }
}
