services:
  remix-base:
    build: .
    image: remix-base:latest

  remix-test:
    image: remix-base:latest
    working_dir: /remix
    command: pnpm run test

  remix-guides:
    image: remix-base:latest
    ports:
      - "44101:44100"
    working_dir: /remix
    command: pnpm --filter remix-guides run dev

  remix-api:
    image: remix-base:latest
    ports:
      - "44102:44100"
    working_dir: /remix
    command: pnpm --filter remix-api run dev

  remix-bookstore:
    image: remix-base:latest
    ports:
      - "44103:44100"
    working_dir: /remix/demos/bookstore
    command: pnpm run dev
