[project]
name = "26"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "hello-maturin",
    "ipython>=9.8.0",
    "maturin>=1.10.2",
    "pytest>=9.0.2",
    "ruff>=0.14.10",
]

[tool.uv.sources]
hello-maturin = { git = "https://github.com/ontouchstart/ontouchstart.github.io", rev = "hello_maturin" }

