#!/usr/bin/env python3
import sys
from mlx_lm import generate, load

# Load model (change to a smaller one if you hit memory limits)
model, tokenizer = load("openai/gpt-oss-20b")

# Read prompt from stdin
prompt = sys.stdin.read()

# Compute token budget
prompt_len = len(tokenizer.encode(prompt))
context_window = 8192  # adjust if you switch models
max_tokens = context_window - prompt_len - 1

if max_tokens <= 0:
    raise ValueError("Prompt is too long for the model's context window.")

# Prepare chat template
conversation = [{"role": "user", "content": prompt}]
tokens = tokenizer.apply_chat_template(
    conversation=conversation,
    add_generation_prompt=True
)

# Print prompt for reference
print("# prompt")
print("```")
print(prompt)
print("```")
print("# Generated by LLM")

# Generate
output = generate(
    model=model,
    tokenizer=tokenizer,
    prompt=tokens,
    max_tokens=max_tokens,
    verbose=True  # set to False for silent mode
)

print(output)
