import sys
from mlx_lm import generate, load
model, tokenizer = load("openai/gpt-oss-20b")
prompt = sys.stdin.read()
print("# prompt")
print("```")
print(prompt)
print("```")
print("# Generated by LLM")
conversation = [{"role": "user", "content": prompt}]
tokens = tokenizer.apply_chat_template(conversation=conversation, add_generation_prompt=True)
print(generate(model=model, tokenizer=tokenizer, prompt=tokens, max_tokens=1024 * 1024, verbose=True))
