[project]
name = "09"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "accelerate>=1.12.0",
    "fastapi[standard]>=0.124.0",
    "gitpython>=3.1.45",
    "ipython>=9.8.0",
    "mlx-lm>=0.28.4",
    "pydantic>=2.12.5",
    "pytest-playwright>=0.7.2",
    "ruff>=0.14.8",
    "torch>=2.9.1",
]
