2026-07-29_18-55-37_conv_b5efbbcd_what_is_ai4science_.md:
	cat ../jsonl/2026-07-29_18-55-37_conv_b5efbbcd_what_is_ai4science_.jsonl | jq .message.content | tail -1 | sed 's/\\n/\n/g' | sed 's/\\"/\"/g' > 2026-07-29_18-55-37_conv_b5efbbcd_what_is_ai4science_.md

2026-07-29_19-21-56_conv_44ebc77e_relate_joseph_knecht.md:
	cat ../jsonl/2026-07-29_19-21-56_conv_44ebc77e_relate_joseph_knecht.jsonl | jq .message.content | tail -1 | sed 's/\\n/\n/g' | sed 's/\\"/\"/g' > 2026-07-29_19-21-56_conv_44ebc77e_relate_joseph_knecht.md

2026-07-29_23-05-05_conv_00ca0c02_review_https_ontouch.md:
	cat ../jsonl/2026-07-29_23-05-05_conv_00ca0c02_review_https_ontouch.jsonl | jq .message.content | tail -1 | sed 's/\\n/\n/g' | sed 's/\\"/\"/g' > 2026-07-29_23-05-05_conv_00ca0c02_review_https_ontouch.md

2026-07-30_18-04-49_conv_f02c4872_chat_7_30_2026_2_02_.md:
	cat ../jsonl/2026-07-30_18-04-49_conv_f02c4872_chat_7_30_2026_2_02_.jsonl | jq .message.content | tail -1 | sed 's/\\n/\n/g' | sed 's/\\"/\"/g' > 2026-07-30_18-04-49_conv_f02c4872_chat_7_30_2026_2_02_.md
