all:
	cargo install --git https://github.com/ontouchstart/ontouchstart.github.io --branch poc_pyo3_rs poc_pyo3_rs --root .cargo
	.cargo/bin/poc_pyo3_rs
	.cargo/bin/this
	.cargo/bin/now
	rm -rf .cargo
