[project]
name = "18"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipython>=9.8.0",
    "ruff>=0.14.10",
    "gist",
    "ask-mlx-lm",
]

[tool.uv.sources]
gist = { git = "https://github.com/ontouchstart/ontouchstart.github.io", rev = "gist" }
ask-mlx-lm = { git = "https://github.com/ontouchstart/ontouchstart.github.io", rev = "ask_mlx_lm" }
