2026-07-24_13-51-13_conv_7bf7091d_follow_the_instructi.md:
	cat 2026-07-24_13-51-13_conv_7bf7091d_follow_the_instructi.jsonl | jq .message.content | tail -1 | sed 's/\\n/\n/g' | sed 's/\\"/\"/g' > 2026-07-24_13-51-13_conv_7bf7091d_follow_the_instructi.md

2026-07-24_15-10-01_conv_6f2191ba_review_following_out.md:
	cat 2026-07-24_15-10-01_conv_6f2191ba_review_following_out.jsonl | jq .message.content | tail -1 | sed 's/\\n/\n/g' | sed 's/\\"/\"/g' > 2026-07-24_15-10-01_conv_6f2191ba_review_following_out.md
