2026-07-24_13-51-13_conv_7bf7091d_follow_the_instructi.md:
	echo `cat 2026-07-24_13-51-13_conv_7bf7091d_follow_the_instructi.jsonl| jq .message.content | tail -1` | sed 's/\\"/\"/g' > 2026-07-24_13-51-13_conv_7bf7091d_follow_the_instructi.md
