2026-07-27_15-00-01_conv_ced18288_https_gist_githubuse.md:
	cat 2026-07-27_15-00-01_conv_ced18288_https_gist_githubuse.jsonl | jq .message.content | tail -1 | sed 's/\\n/\n/g' | sed 's/\\"/\"/g' > 2026-07-27_15-00-01_conv_ced18288_https_gist_githubuse.md
2026-07-27_15-18-41_conv_949c0b41_https_ontouchstart_g.md:
	cat 2026-07-27_15-18-41_conv_949c0b41_https_ontouchstart_g.jsonl | jq .message.content | tail -1 | sed 's/\\n/\n/g' | sed 's/\\"/\"/g' > 2026-07-27_15-18-41_conv_949c0b41_https_ontouchstart_g.md

