up:
	docker compose up everything
down:
	docker compose down
dev:
	docker compose run --remove-orphans --rm dev bash

everything-dev:
	docker compose exec everything bash

modelcontextprotocol:
	git clone https://github.com/modelcontextprotocol/modelcontextprotocol.git
typescript-sdk:
	git clone https://github.com/modelcontextprotocol/typescript-sdk
servers:
	git clone https://github.com/modelcontextprotocol/servers.git
clean:
	rm -rf servers modelcontextprotocol
