up:
	docker compose up
down:
	docker compose down
servers-dev:
	docker compose run --remove-orphans --rm servers bash
everything-dev:
	docker compose exec everything bash

modelcontextprotocol:
	git clone https://github.com/modelcontextprotocol/modelcontextprotocol.git
typescript-sdk:
	git clone https://github.com/modelcontextprotocol/typescript-sdk
servers:
	git clone https://github.com/modelcontextprotocol/servers.git
clean:
	rm -rf servers modelcontextprotocol
