services:
  dev:
    build: .
    volumes:
      - ./bun:/bun
      - ./deno:/deno
      - ./node:/node
      - ./playwright:/playwright
    networks:
      - bun
      - deno

  playwright-browser:
    build: .
    volumes:
      - ./playwright:/playwright
    working_dir: /playwright/browser
    command: ["npx", "playwright", "show-report", "--host", "0.0.0.0"] 
    ports:
      - 9323:9323

  playwright-bun:
    build: .
    volumes:
      - ./playwright:/playwright
    working_dir: /playwright/bun
    command: ["npx", "playwright", "show-report", "--host", "0.0.0.0"]
    ports:
      - 9324:9323

  playwright-deno:
    build: .
    volumes:
      - ./playwright:/playwright
    working_dir: /playwright/deno
    command: ["npx", "playwright", "show-report", "--host", "0.0.0.0"]
    ports:
      - 9325:9323

  bun-react:
    build: .
    volumes:
      - ./bun:/bun
    working_dir: /bun/react
    command: ["bun", "run", "start"]
    ports:
      - 3001:3000
    networks:
      - bun

  bun-react-blank:
    build: .
    volumes:
      - ./bun:/bun
    working_dir: /bun/react-blank
    command: ["bun", "run", "start"]
    ports:
      - 3002:3000
    networks:
      - bun

  bun-react-tailwind:
    build: .
    volumes:
      - ./bun:/bun
    working_dir: /bun/react-tailwind
    command: ["bun", "run", "start"]
    ports:
      - 3003:3000
    networks:
      - bun

  deno-react:
    build: .
    volumes:
      - ./deno:/deno
    working_dir: /deno/deno-react
    command: ["deno", "task", "dev"]
    ports:
      - 5173:5173
    networks:
      - deno

networks:
  bun: 
  deno: 

