dev:
	docker compose run --rm --remove-orphans dev bash
version:
	docker compose run --rm --remove-orphans dev pi --version 1> version.1.log 2> version.2.log
build:
	docker compose build --no-cache 1> build.1.log 2> build.2.log
