all:
	echo "# Who is Jim Henson? " > README.md
	echo "- [YouTube](https://www.youtube.com/watch?v=ThzNQaqgUsM)" >> README.md
	echo >> README.md
	echo "main.py" >> README.md
	echo '```' >> README.md
	cat -n main.py >> README.md
	echo '```' >> README.md
	echo '```' >> README.md
	echo "uv run main.py " >> README.md
	uv run main.py >> README.md
	echo '```' >> README.md
