test:
	cargo install cargo-expand
	cargo --version
	cargo update
	cargo fmt
	cargo expand -p github_url_2026_01_09_rs
	cargo expand -p github_url_2026_01_09_rs --test github_url_2026_01_09_rs
	cargo expand -p github_url_2026_01_09_rs --test url
	cargo test -p github_url_2026_01_09_rs

