all:
	echo "# 2025/11/25" > README.md	
	echo "## Tokenizer matters" >> README.md

	echo '`FastAPI/mlx-community/Mistral-7B-Instruct-v0.3/what-is-ChatGPT-tokens.json`' >> README.md
	echo >> README.md
	echo '```' >> README.md
	cat -n FastAPI/mlx-community/Mistral-7B-Instruct-v0.3/what-is-ChatGPT-tokens.json >> README.md
	echo '```' >> README.md

	echo '`FastAPI/Qwen/Qwen3-30B-A3B-MLX-4bit/what-is-ChatGPT-tokens.json`' >> README.md
	echo >> README.md
	echo '```' >> README.md
	cat -n FastAPI/Qwen/Qwen3-30B-A3B-MLX-4bit/what-is-ChatGPT-tokens.json >> README.md
	echo '```' >> README.md

	echo '`FastAPI/openai/gpt-oss-20b/what-is-ChatGPT-tokens.json`' >> README.md
	echo >> README.md
	echo '```' >> README.md
	cat -n FastAPI/openai/gpt-oss-20b/what-is-ChatGPT-tokens.json >> README.md
	echo '```' >> README.md
