# https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md
name: Makefile CI (macos-26)

on:
  push:
    branches: [ "2026_01_13_rs" ]

jobs:
  build:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v6
    - uses: ontouchstart/rust-toolchain@master
    - run: cargo test --all-features
      with:
        toolchain: stable
    - name: Make
      run: make
