name: Makefile CI

on:
  push:
    branches: [ "2026_01_07_rs" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@stable
    - name: Make
      run: make
