name: Makefile CI

on:
  push:
    branches: [ "ask_mlx_lm" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Install dependencies
      run: make
