# https://github.com/actions/runner-images/blob/main/images/ubuntu-slim/ubuntu-slim-Readme.md
name: Makefile CI (ubuntu-slim)

on: push

jobs:
  build:

    runs-on: ubuntu-slim

    steps:
    - uses: actions/checkout@v6
    - run: make
