# https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
name: Makefile CI (ubuntu-24.04)

on: push

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6
    - uses: ontouchstart/rust-toolchain
    - uses: ontouchstart/setup-uv
    - run: make
